import { jsPDF } from "jspdf";

const generateResumePDF = (profileImage, resumeData) => {
  const doc = new jsPDF();

  // Define Colors
  const primaryColor = [0, 102, 204]; // Blue
  const secondaryColor = [34, 34, 34]; // Dark Gray
  const textColor = [255, 255, 255]; // White

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, "F"); // Header background
  doc.setFontSize(30);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text(resumeData.firstName, 105, 25, null, null, "center");

  // Subtitle
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.text("Software Developer", 105, 35, null, null, "center");

  // Profile Image
  const imageX = 15;
  const imageY = 45;
  const imageDiameter = 60;
  const radius = imageDiameter / 2;
  if (profileImage) {
    // Draw circular background
    doc.setFillColor(255, 255, 255); // White background
    doc.ellipse(imageX + radius, imageY + radius, radius, radius, "F"); // Circular background

    // Add profile image
    doc.addImage(
      profileImage,
      "PNG",
      imageX,
      imageY,
      imageDiameter,
      imageDiameter,
      undefined,
      "PNG",
      0
    ); // Adjust position and size as needed
  }

  // Contact Information Box
  doc.setFillColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.roundedRect(15, 115, 180, 35, 5, 5, "F"); // Rounded rectangle background for contact info
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.text(`Email: ${resumeData.email}`, 20, 125);
  doc.text(`Phone: ${resumeData.mobileNumber}`, 20, 135);
  doc.text(`Description: ${resumeData.description}`, 20, 145);
  doc.text("LinkedIn: linkedin.com/in/johndoe", 20, 165);
  doc.text("GitHub: github.com/johndoe", 20, 175);

  // Section Title: Education
  doc.setFontSize(18);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text("Education", 15, 350);

  // Education Details
  doc.setFontSize(12);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFont("helvetica", "normal");
  doc.text("Bachelor of Science in Computer Science", 15, 360);
  doc.text("University of Example", 15, 370);
  doc.text("Graduated: 2017", 15, 380);

  // Section Title: Skills
  doc.setFontSize(18);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFont("helvetica", "bold");
  doc.text("Skills", 15, 410);

  // Skills Details
  doc.setFontSize(12);
  doc.setTextColor(secondaryColor[0], secondaryColor[1], secondaryColor[2]);
  doc.setFont("helvetica", "normal");
  doc.text(
    "• React.js\n• Node.js\n• JavaScript\n• HTML & CSS\n• RESTful APIs\n• Git\n• Agile Methodologies",
    15,
    420,
    { maxWidth: 180 }
  );

  // Footer
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 285, 210, 15, "F"); // Footer background
  doc.setFontSize(10);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by jsPDF", 105, 292, null, null, "center");

  doc.save("resume.pdf");
};

export default generateResumePDF;
